export const SliderData = [
    {
      image:
        '/../public/img-1.jpg',
    },
    {
      image:
      '/../public/img-2.jpg',
    },
    {
      image:
      '/../public/img-3.jpg',
    },
    {
      image:
      '/../public/img-4.jpg',
    },
    {
      image:
      '/../public/img-5.jpg',
    },
    {
      image:
        '/../public/img-6.jpg',
    },
    {
      image:
      '/../public/img-7.jpg',
    },
    {
      image:
      '/../public/img-8.jpg',
    },
    {
      image:
      '/../public/img-9.jpg',
    },
    {
      image:
      '/../public/img-10.jpg',
    },
    {
      image:
        '/../public/img-11.jpg',
    },
    {
      image:
      '/../public/img-12.jpg',
    },
    {
      image:
      '/../public/img-13.jpg',
    },
    {
      image:
      '/../public/img-14.jpg',
    },
    {
      image:
      '/../public/img-15.jpg',
    },
    {
      image:
        '/../public/img-16.jpg',
    },
    {
      image:
      '/../public/img-17.jpg',
    },
    {
      image:
      '/../public/img-18.jpg',
    },
    {
      image:
      '/../public/img-19.jpg',
    },
  ];
  